### ISSUE TITLE
To Abstract Exceptions Thrown by _Nodes and _Edges

### ISSUE THREAD

**Issue by BgRva** [BgRva/x.Graph#1]
If an exception is thrown by the _Nodes or _Edges dictionaries in the Graph class, the exception may be tied to the implementation.  For example, if the user tries to do 

```csharp
var graph = new Graph<int>();
graph.Add(33);
graph.Add(33);
```

this will throw a ArgumentException() (see https://msdn.microsoft.com/en-us/library/k7z0zy8k(v=vs.110).aspx ) since the key already exists.  Do we catch this and throw our own exception in order to abstract away the fact that we are using a dictionary here?  Maybe later or for another implementation we don't use a dictionary?  I say we catch any dictionary specific exceptions and throw our own so we will have a consistent set of exceptions being thrown.

**Comment by Vekyllis** [comment]
I agree - we should have our own exception(s)for consistency purposes. It may be that we will move away from dictionaries in the future.

**Comment by Vekyllis** [comment]
For the existence of a unique ID for node as in G[1], I just have it return a null if the node does not exist in G.  I figured it might be best to let a higher-level program handle nulls rather than throw an exception for a non-existent node?  What do you think?

**Comment by Vekyllis** [comment]
For the AddNode functionality, I throw an exception if the node already exists.

**Comment by BgRva** [comment]
Yep, I agree with your last two approaches.  For the exceptions, we should use existing exception classes like you are currently doing, rather than rolling our own.  Unless this becomes absolutely necessary.

**Comment by Vekyllis** [comment]
Completed.
